Bin: update pbcopy and pbpaste to work with wayland

diff --git a/bin/pbcopy b/bin/pbcopy
--- a/bin/pbcopy
+++ b/bin/pbcopy
@@ -1,10 +1,19 @@
 #!/usr/bin/env bash
 
-if hash xsel &>/dev/null; then
-    xsel --clipboard --input "$@"
-elif hash xclip &>/dev/null; then
-    xclip -selection clipboard "$@"
-else
-    echo "xsel or xclip is required" >&2
-    exit 1
+if [ "$XDG_SESSION_TYPE" = "x11" ]; then
+    if hash xsel &>/dev/null; then
+        xsel --clipboard --input "$@"
+    elif hash xclip &>/dev/null; then
+        xclip -selection clipboard "$@"
+    else
+        echo "xsel or xclip is required" >&2
+        exit 1
+    fi
+elif [ "$XDG_SESSION_TYPE" = "wayland" ]; then
+    if hash wl-copy &>/dev/null; then
+        wl-copy "$@"
+    else
+        echo "wl-clipboard is required" >&2
+        exit 1
+    fi
 fi
